### ISSUE TITLE
doubt about installation on mac and mesh shape

### ISSUE THREAD

**Issue by Mc210** [fangohr/finmag#33]
Is posible install finmag on mac?.

Is there a document that contains installation instructions and examples?

What kind of cells can I build with this program?, triangular or hexagonal cells is it possible to build?

**Comment by rpep** [comment]
Hi @Mc210 

Yes, it is possible, though it is not advisable. To run any meaningful simulations, you are going to need to run on at least a high-end desktop machine and we recommend Linux. 

We only support installation through Docker because of the complicated dependencies of Finmag. Please see the readme file on the homepage.

Tetragonal cells are supported - you can output meshes from programs like Gmsh.

Examples are here: https://github.com/fangohr/finmag/tree/master/doc/ipython_notebooks_src
They are not all currently working as Finmag is not currently under active development.

**Comment by marijanbeg** [comment]
I believe this issue has been addressed by @ryanpepper and I will close it now. Thank you!
